final _college = [
  "Select College Name",
  "Acharya Narendra Dev College",
  "Aditi Mahavidyalaya",
  "Agricultural Economics Research Centre",
  "Ahilya Bai College of Nursing",
  "Amar Jyoti Institute of Physiotherapy",
  "Aryabhatta College(Formally Ram Lal Anand College-Evg.)",
  "Atma Ram Sanatan Dharma College",
  "Ayurvedic & Unani Tibia College",
  "Bhagini Nivedita College",
  "Bharati College",
  "Bhaskaracharya College of Applied Sciences",
  "Bhim Rao Ambedkar College",
  "School of Open Learning (SOL)",
  "Centre for Detector & Related Software Technology",
  "Centre for Environmental Management of Degraded Ecosystems (CEMDE)",
  "Centre for Genetic Manipulation of Crop Plants",
  "Centre for Global Studies",
  "Centre for Himalayan Studies",
  "Centre for India-Canada Studies",
  "Centre for Innovation in Infectious Disease Research, Education and Training (CIIDRET)",
  "Centre for Interdisciplinary Studies of Mountain and Hill Environment",
  "Centre for Science Education & Communication",
  "Chacha Nehru Bal Chikitsalaya",
  "Cluster Innovation Centre (CIC)",
  "College of Art",
  "College of Nursing at Army Hospital (R&R)",
  "College of Vocational Studies",
  "Daulat Ram College",
  "Deen Dayal Upadhyaya College",
  "Delhi College of Arts & Commerce",
  "Delhi Institute of Pharmaceutical Sciences and Research",
  "Delhi School of Economics",
  "Deshbandhu College(Morning)",
  "Dr. B.R. Ambedkar Center for Biomedical Research (ACBR)",
  "Durga Bai Deshmukh College of Special Edu.(VI)",
  "Dyal Singh College",
  "Dyal Singh College (Evening)",
  "Florence Nightingale College of Nursing",
  "Gargi College",
  "Hans Raj College",
  "Hindu College",
  "Holy Family College of Nursing",
  "Indira Gandhi Institute of Physical Education & Sports Sciences",
  "Indraprastha College for Women",
  "Institute of Home Economics",
  "Institute of Informatics & Communication(IIC)",
  "Institute of Lifelong Learning(ILLL)",
  "Inter Disciplinary Centre for Plant Genomics",
  "Janki Devi Memorial College",
  "Jesus & Mary College",
  "Kalindi College for Women",
  "Kamla Nehru College for Women",
  "Keshav Mahavidyalaya",
  "Kirori Mal College",
  "Lady Hardinge Medical College",
  "Lady Irwin College",
  "Lady Shri Ram College for Women",
  "Lakshmi Bai College for Women",
  "Maharaja Agarsen College",
  "Maharshi Valmiki College of Education",
  "Maitreyi College for Women",
  "Mata Sundri College for Women",
  "Maulana Azad Institute of Dental Sciences",
  "Maulana Azad Medical College",
  "Miranda House",
  "Moti Lal Nehru College",
  "Moti Lal Nehru College (Evening)",
  "University College of Medical Sciences",
  "Nehru Homeopathic Medical College & Hospital",
  "Netaji Subhash Institute of Technology",
  "P.G.D.A.V. College",
  "P.G.D.A.V. College (Evening)",
  "Prof. D.S. Kothari Centre for Science Ethics & Education",
  "Pt. Deendayal Upadhyaya Institute of Physically Handicapped",
  "Rajdhani College",
  "Rajkumari Amrit Kaur College of Nursing",
  "Ram Lal Anand College",
  "Ramanujan College",
  "Ramjas College",
  "Satyawati College",
  "Satyawati College (Evening)",
  "School of Open Learning ( Erstwhile School of Correspondence & Continuing Education)",
  "School of Rehabilitation Sciences",
  "Shaheed Bhagat Singh College",
  "Shaheed Bhagat Singh College (Evening)",
  "Shaheed Rajguru College of Applied Sciences for Women",
  "Shaheed Sukhdev College of Business Studies",
  "Shivaji College",
  "Shri Ram College of Commerce",
  "Shyam Lal College",
  "Shyam Lal College (Evening)",
  "Shyama Prasad Mukherji College for Women",
  "Sri Aurobindo College",
  "Sri Aurobindo College (Evening)",
  "Sri Guru Gobind Singh College of Commerce",
  "Sri Guru Nanak Dev Khalsa College",
  "Sri Guru Tegh Bahadur Khalsa College",
  "Sri Venkateswara College",
  "St. Stephen's College",
  "Swami Shraddhanand College",
  "Vallabhbhai Patel Chest Institute",
  "Vivekananda College",
  "Women Studies & Development Centre (WSDC)",
  "Zakir Husain Delhi College",
  "Zakir Husain Post Graduate Evening College"
];
