// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxIsUleSzV3P8GZBwjX1VfE8VwksHFVY0',
    appId: '1:530128623193:web:99477d58f29b3fe5ea0348',
    messagingSenderId: '530128623193',
    projectId: 'dhamni-818db',
    authDomain: 'dhamni-818db.firebaseapp.com',
    storageBucket: 'dhamni-818db.appspot.com',
    measurementId: 'G-415PC91NE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACA1nK9zw3oJe8OTXUwEiTywfidBHb5xI',
    appId: '1:530128623193:android:6a3b22545207086aea0348',
    messagingSenderId: '530128623193',
    projectId: 'dhamni-818db',
    storageBucket: 'dhamni-818db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7JJU2xDdWMh1LubLKaSreL8GOUkoenfA',
    appId: '1:530128623193:ios:209de64eecb18ff3ea0348',
    messagingSenderId: '530128623193',
    projectId: 'dhamni-818db',
    storageBucket: 'dhamni-818db.appspot.com',
    androidClientId: '530128623193-bj1q7be3ep4gr1qr4mkds3eecq81g2qm.apps.googleusercontent.com',
    iosClientId: '530128623193-7oe2119itihaqhdtmd0n1n7gtodm9oh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhamni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7JJU2xDdWMh1LubLKaSreL8GOUkoenfA',
    appId: '1:530128623193:ios:209de64eecb18ff3ea0348',
    messagingSenderId: '530128623193',
    projectId: 'dhamni-818db',
    storageBucket: 'dhamni-818db.appspot.com',
    androidClientId: '530128623193-bj1q7be3ep4gr1qr4mkds3eecq81g2qm.apps.googleusercontent.com',
    iosClientId: '530128623193-7oe2119itihaqhdtmd0n1n7gtodm9oh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhamni',
  );
}
