// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcOpdWSExM4rwukouH6zlW6YkyFQwwy5w',
    appId: '1:337462199984:web:90702024cc1541013e5d75',
    messagingSenderId: '337462199984',
    projectId: 'dhamniapp',
    authDomain: 'dhamniapp.firebaseapp.com',
    databaseURL: 'https://dhamniapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dhamniapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD01hWhLo1bZ72RRQexOA8ZCYnY6byUJ0Y',
    appId: '1:337462199984:android:08b67b1cac698ffb3e5d75',
    messagingSenderId: '337462199984',
    projectId: 'dhamniapp',
    databaseURL: 'https://dhamniapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dhamniapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwe2CMvv1Oi6spYqWqmDRzVDrTMbY7ymE',
    appId: '1:337462199984:ios:5ac50746cdb253a13e5d75',
    messagingSenderId: '337462199984',
    projectId: 'dhamniapp',
    databaseURL: 'https://dhamniapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dhamniapp.appspot.com',
    androidClientId: '337462199984-l1eig1eeghlue8hic1lalp5lf1hvv6cp.apps.googleusercontent.com',
    iosClientId: '337462199984-ri7gccr4o1jikvjohl6v1vlfp9sc02sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhamni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwe2CMvv1Oi6spYqWqmDRzVDrTMbY7ymE',
    appId: '1:337462199984:ios:5ac50746cdb253a13e5d75',
    messagingSenderId: '337462199984',
    projectId: 'dhamniapp',
    databaseURL: 'https://dhamniapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dhamniapp.appspot.com',
    androidClientId: '337462199984-l1eig1eeghlue8hic1lalp5lf1hvv6cp.apps.googleusercontent.com',
    iosClientId: '337462199984-ri7gccr4o1jikvjohl6v1vlfp9sc02sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhamni',
  );
}
